id: P002936
initial_creation_type: ocr
source_metadata:
  id: bdr:W20023
  title: བོད་ཀྱི་རིག་གནས་གོང་འཕེལ་དང་སློབ་གསོའི་རྣམ་བཤད།
  author: ''
  volumes:
    8f644fcbf7224f11a7890712fcb1eee8:
      image_group_id: I4796
      title: ''
      volume_number: 1
      total_pages: 312
