id: P002936
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:29:28.699859
source_metadata:
  id: bdr:W20023
  title: བོད་ཀྱི་རིག་གནས་གོང་འཕེལ་དང་སློབ་གསོའི་རྣམ་བཤད།
  author: ''
  volumes:
    8f644fcbf7224f11a7890712fcb1eee8:
      image_group_id: I4796
      title: ''
      volume_number: 1
      total_pages: 312
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
