id: I46761866
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:10:52+00:00'
last_modified: '2022-06-07T16:19:51.981528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20023
  title: བོད་ཀྱི་རིག་གནས་གོང་འཕེལ་དང་སློབ་གསོའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4096':
      image_group_id: I4796
      title: ''
      total_pages: 312
      order: 1
      base_file: 4096.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
